### ISSUE TITLE
Error on load_img_name_list function

### ISSUE THREAD

**Issue by Spritea** [CVI-SZU/CLIMS#15]
Hi, thanks for your great work!

However, I met an error when run the new version of CLIMS. The error information is shown below.

```
Traceback (most recent call last):
  File "run_sample.py", line 144, in <module>
    step.train_clims.run(args)
  File "/home/wensheng/code/for_dev/CLIMS/step/train_clims.py", line 66, in run
    train_dataset = voc12.dataloader.VOC12ClassificationDataset(args.train_list, voc12_root=args.voc12_root,
  File "/home/wensheng/code/for_dev/CLIMS/voc12/dataloader.py", line 167, in __init__
    super().__init__(img_name_list_path, voc12_root,
  File "/home/wensheng/code/for_dev/CLIMS/voc12/dataloader.py", line 118, in __init__
    self.img_name_list = load_img_name_list(img_name_list_path)
  File "/home/wensheng/code/for_dev/CLIMS/voc12/dataloader.py", line 62, in load_img_name_list
    img_name_list = np.loadtxt(dataset_path, dtype=np.int32)
  File "/home/wensheng/anaconda3/envs/clims/lib/python3.8/site-packages/numpy/lib/npyio.py", line 1338, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
  File "/home/wensheng/anaconda3/envs/clims/lib/python3.8/site-packages/numpy/lib/npyio.py", line 999, in _read
    arr = _load_from_filelike(
ValueError: could not convert string '2007_000032' to int32 at row 0, column 1.
```
 The problem is in the `load_img_name_list` function ([here](https://github.com/CVI-SZU/CLIMS/blob/abb4ac1b9157b7cf2e76a6124eb78d6e4e4f74d1/voc12/dataloader.py#L62)). 

Since the text in the `train_aug.txt` is like `2007_000032`, while the `load_img_name_list` function tries to load the txt by `img_name_list = np.loadtxt(dataset_path, dtype=np.int32)`, which causes problem. I guess we will need to modify either the `train_aug.txt` to remove the middle underline `_`, or adjust the `load_img_name_list` function.

Could you check, thanks!

**Comment by Sierkinhane** [comment]
Hi, maybe updating numpy version to 1.20.2 will work for this issue.

**Comment by Spritea** [comment]
My numpy version is 1.23.5. Is this too high?

**Comment by Sierkinhane** [comment]
Try `pip install numpy==1.20.2`.

**Comment by Sierkinhane** [comment]
Hi, have you solved the problem? :-)

**Comment by Spritea** [comment]
Hi, I have tried numpy v1.20.2, and it works with current `train_aug.txt` file!

Thanks for your help!
