### ISSUE TITLE
读取数据集出现错误

### ISSUE THREAD

**Issue by y276624172** [CVI-SZU/CLIMS#20]
Traceback (most recent call last):
  File "/media/jk1803/E/jc/CLIMS-master/run_sample.py", line 144, in <module>
    step.train_clims.run(args)
  File "/media/jk1803/E/jc/CLIMS-master/step/train_clims.py", line 69, in run
    train_dataset = voc12.dataloader.VOC12ClassificationDataset(args.train_list, voc12_root=args.voc12_root,
  File "/media/jk1803/E/jc/CLIMS-master/voc12/dataloader.py", line 167, in __init__
    super().__init__(img_name_list_path, voc12_root,
  File "/media/jk1803/E/jc/CLIMS-master/voc12/dataloader.py", line 118, in __init__
    self.img_name_list = load_img_name_list(img_name_list_path)
  File "/media/jk1803/E/jc/CLIMS-master/voc12/dataloader.py", line 62, in load_img_name_list
    img_name_list = np.loadtxt(dataset_path, dtype=np.int32)
  File "/home/jk1803/anaconda3/envs/CLIMs/lib/python3.8/site-packages/numpy/lib/npyio.py", line 1338, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
  File "/home/jk1803/anaconda3/envs/CLIMs/lib/python3.8/site-packages/numpy/lib/npyio.py", line 999, in _read
    arr = _load_from_filelike(
ValueError: could not convert string '2007_000032' to int32 at row 0, column 1.

**Comment by y276624172** [comment]
> This [issue](https://github.com/CVI-SZU/CLIMS/issues/15) can help you.

Thank you for help
